[package]
name = "nui_finance"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
version = "0.0.1"
# published-at = "0x56e98b66b7eb9518d96b014e2c3af0c5112b3990927bc5648312ac40b7ee0e03"
published-at = "0xe3ac978e16b713ef0fe95282df49db7e6e4d54f987f5869b21730ec3dcfad122"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
SuiSystem = {git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "framework/mainnet"}
ScallopProtocol = {local = "./scallop/protocol"}
spool = { local = "./scallop/spool" }
BucketProtocol = {git = "https://github.com/Bucket-Protocol/bucket-interface.git", subdir = "bucket-protocol", rev = "main"}
Flask = { git = "https://github.com/Sparkling-Finance/contract.git", subdir = "flask", rev = "sbuck"}
BucketFountain = { git = "https://github.com/Bucket-Protocol/fountain.git", subdir = "", rev = "mainnet"}

[addresses]
nui_finance = "0x0"
